{{- if .Values.global.secrets.minio.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-system-init
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Release.Name }}-system-init
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
    spec:
      restartPolicy: Never
      containers:
      - name: main
        image:
          repository: sonikap/archival_be
          pullPolicy: Always
          tag: "system_init_new1"
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-cloud-env
{{- end }}