# Default values for orc-event-retry-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

redisServer: "localhost:6379"
kafkaBroker: "localhost:9092"
kafkaTopic: "orc-event-retry"
reattemptSendToKafka: 5
sortedSetKey: "my_sorted_set"
hashSetKey: "my_hash_set"
retryBucket: 15

replicaCount: 1

image:
  repository: sonikap/archival_be
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "orc_event_retry_new2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

schedule: '*/15 * * * *'

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}