{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sf-presto.fullname" . }}-coordinator
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: resource-manager
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sf-presto.fullname" . }}-coordinator
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleDownPeriod }}
        value: 1
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Pods
        periodSeconds: {{ .Values.autoscaling.scaleUpPeriod }}
        value: 1
  minReplicas: {{ .Values.autoscaling.coordinator.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.coordinator.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.coordinator.targetAverageUtilization }}
{{- end }}
